### ISSUE TITLE
One-shot vm not getting gce preemptible event and not retry

### ISSUE THREAD

**Issue by litan1106** [jenkinsci/google-compute-engine-plugin#148]
Cannot contact ubuntu-1804-lts-spot-ojrbv0: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on ubuntu-1804-lts-spot-ojrbv0 failed. The channel is closing down or has closed down
Cancelling nested steps due to timeout
Could not connect to ubuntu-1804-lts-spot-ojrbv0 to send interrupt signal to process

ubuntu-1804-lts-spot-ojrbv0 was marked offline: Connection was broken: java.io.EOFException
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2763)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3258)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:873)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:350)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)

**Comment by stephenashank** [comment]
Hi @litan1106, can you tell me more about this One Shot VM?
If I understand the question correctly, you would have the boxes for "One Shot" and "Preemptible" checked for this configuration, right?
Also, what is the "Node Retention Time" for the configuration?

**Comment by litan1106** [comment]
@stephenashank correct. here is my settings

Node Retention Time: 6
Number of Executors: 1
Launch Timeout: 300
One-Shot: checked
Preemptible?: checked

**Comment by stephenashank** [comment]
@litan1106 After attempting to reproduce this I think I have an idea of what is going on. Whether you were manually testing preemption through "simulate-maintenance-event" or had unfortunate luck with limited resource availability in the VM's zone, it seems that the machine may have been preempted too early in the launch cycle.

In order to check for a preemption event, we need to connect to the agent over ssh, then install and run the jenkins agent jar. Once that is done we are able to run a process on the agent which checks for the "preempted" value being changed in the instance metadata, which is how GCP gives warning for this. Currently we only restart the jobs under this specific circumstance. So, if the listener is added before the preempted instance is shut down but after the preempted flag is set, no change will be detected and it will timeout instead of canceling and restarting the job.

This should be a rare occurrence, but I think it can be mitigated by checking whether the instance is already preempted right after launching, most likely in the same place as the current listener. There may still be a rare case where the preemption event occurs between checking the initial value and then making the request that waits for a change.

Thanks for submitting the issue and bringing this to our attention.
