### ISSUE TITLE
google-oauth-plugin update breaks GCP agents

### ISSUE THREAD

**Issue by rkirkpat** [jenkinsci/google-compute-engine-plugin#153]
Just upgraded 'google-oauth-plugin' to v1.0.0 this morning and after master restart attempts to launch GCP agents I am getting this error repeatedly in the master's log:
```
2019-10-30 16:14:45.805+0000 [id=29]	INFO	c.g.j.p.c.ComputeEngineCloud#provision: Provisioning node from configs [com.google.jenkins.plugins.computeengine.InstanceConfiguration@6eb97f88] for excess workload of 1 units of label 'linux&&python'
2019-10-30 16:14:46.185+0000 [id=29]	INFO	c.g.j.p.c.ComputeEngineCloud#availableNodeCapacity: Found capacity for 4 nodes in cloud Google Sandbox Agents
2019-10-30 16:14:46.332+0000 [id=29]	SEVERE	hudson.triggers.SafeTimerTask#run: Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@650519c9 failed
java.lang.NoClassDefFoundError: Could not initialize class com.google.common.io.BaseEncoding
	at org.jclouds.ssh.SshKeys.encodeAsOpenSSH(SshKeys.java:158)
	at org.jclouds.ssh.SshKeys.generate(SshKeys.java:151)
	at org.jclouds.ssh.SshKeys.generate(SshKeys.java:142)
	at com.google.jenkins.plugins.computeengine.ssh.GoogleKeyPair.generate(GoogleKeyPair.java:35)
	at com.google.jenkins.plugins.computeengine.InstanceConfiguration.configureSSHKeyPair(InstanceConfiguration.java:430)
	at com.google.jenkins.plugins.computeengine.InstanceConfiguration.instance(InstanceConfiguration.java:364)
	at com.google.jenkins.plugins.computeengine.InstanceConfiguration.provision(InstanceConfiguration.java:298)
	at com.google.jenkins.plugins.computeengine.ComputeEngineCloud.provision(ComputeEngineCloud.java:253)
	at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:729)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:332)
	at hudson.slaves.NodeProvisioner.access$900(NodeProvisioner.java:63)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:823)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The 'google-compute-engine-plugin' is at the latest available, 4.0.0, Jenkins just upgraded to 2.190.2 LTS. If I downgrade the 'google-oauth-plugin' to 0.10 then I am able to launch GCP agents fine:
```
2019-10-30 16:24:47.430+0000 [id=24]	INFO	c.g.j.p.c.ComputeEngineCloud#provision: Provisioning node from configs [com.google.jenkins.plugins.computeengine.InstanceConfiguration@2f8470ca] for excess workload of 1 units of label 'linux&&python'
2019-10-30 16:24:47.896+0000 [id=24]	INFO	c.g.j.p.c.ComputeEngineCloud#availableNodeCapacity: Found capacity for 4 nodes in cloud Google Sandbox Agents
2019-10-30 16:24:49.973+0000 [id=24]	INFO	c.g.j.p.c.InstanceConfiguration#provision: Sent insert request for instance configuration [Linux Python Agent]
2019-10-30 16:24:49.977+0000 [id=172]	INFO	c.g.j.p.c.ComputeEngineComputerLauncher#launch: Launch will wait 300000 for operation operation-1572452688555-596232bed6cd5-1368de4a-36904892 to complete...
2019-10-30 16:24:49.987+0000 [id=24]	INFO	h.s.NodeProvisioner$StandardStrategyImpl#apply: Started provisioning jenkins-linux-python-ch1v68 from gce-Google Sandbox Agents with 4 executors. Remaining excess workload: -3.494
2019-10-30 16:24:49.987+0000 [id=174]	INFO	c.g.j.p.c.ComputeEngineCloud#lambda$getPlannedNodeFuture$0: Waiting 300000ms for node jenkins-linux-python-ch1v68 to connect
```

Maybe a compatibility issue? Not a show stopper, with the downgrade I am fine.

**Comment by rkirkpat** [comment]
Thanks, I upgrade to v4.1.0 of the 'Google Compute Engine' plugin, as well as version 1.0.0 of the 'Google OAuth Credentials' plugin, and restarted my Jenkins master. Went to Manage Jenkins -> Configure System to review cloud settings and got an oops:
![image](https://user-images.githubusercontent.com/19275599/67971157-ddd57000-fbd1-11e9-9bc0-bf52e5583349.png)

In the master's logs found this full stack trace as well:  [jenkins.log](https://github.com/jenkinsci/google-compute-engine-plugin/files/3795097/jenkins.log)

I only had a pretty basic single cloud configured, nothing exotic, so looks like something else broke...

**Comment by mattdlh** [comment]
We are also having issues with GCP cloud config after the update. Jenkins hangs on "loading" for the main configure page, unless all GCP cloud entries are removed from the config (manually). New GCP entries can no longer be added to the list of clouds in Jenkins config with the following stack trace in jenkins logs:

[jenkins.log](https://github.com/jenkinsci/google-compute-engine-plugin/files/3795728/jenkins.log)

**Comment by stephenashank** [comment]
@rkirkpat @mattdlh With version 4.1.1 these issues should be resolved. I was able to reproduce this behavior with 4.1.0. I didn't catch it originally due to using an outdated version of the 4.1.0 snapshot when testing.

With the 4.1.1 snapshot, I didn't encounter these problems. When that version hits the update center, let me know if that fixes the issues for you as well.

**Comment by lienerieksta** [comment]
4.1.1 fixed the issue of configure page hanging for me.

**Comment by mattdlh** [comment]
Configure page back to loading for us as well on 4.1.1. Thank you @stephenashank

**Comment by rkirkpat** [comment]
Confirmed, v4.1.1 of the 'Google Compute Engine' resolves all of the issues I reported above. Now able to build with GCP agents once again. Thanks!
