### ISSUE TITLE
Launched VMs are shut down during builds

### ISSUE THREAD

**Issue by mattdlh** [jenkinsci/google-compute-engine-plugin#157]
We have been using this plugin successfully for some time, but recently started having VMs be shut down mid-build. For example, a job that uses a GCP cloud will start, spin up a VM in GCP, and begin running on the VM; after about 45m-1hr the build will fail with a `Unexpected termination of the channel` and the VM will show `stopping` in the GCP console.

Looking at the stackdriver logs in GCP, it appears the API call comes from Jenkins to shut the VM off mid-build. In the Jenkins sytem logs, only the disconnect error itself shows, nothing from the GCE plugin regarding why the VM was terminated. For example:

```
I/O error in channel jenkins-slave-w8qs5x
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2638)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3113)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
```

Using the latest version of all plugins. Following variables set for the cloud:
Instance cap: 1
Node Retention Time: 6
Launch Timeout: 600
And using instance template. Have tried tweaking all of the above settings with same result.

**Comment by dmitriykanarskiy** [comment]
Also have this issue, would appreciate any help

**Comment by stephenashank** [comment]
@mattdlh, @dmitriykanarskiy thanks for reporting this. Can you look at the System logs for Jenkins  and tell me if you see anything from this plugin regarding the "node cleanup work" when this happens?

Can you also tell me these configuration settings:
- One-Shot: Enabled
- Windows?
- Preemptible? (Or Preemptibility in the instance template)

Thanks.

**Comment by mattdlh** [comment]
@stephenashank Looking through the logs I do not see anything regarding "node cleanup work" around when this happens (or at all). I see no messages from the plugin in the jenkins logs at all around the shutdown event.

One-Shot: unchecked
Windows: no
Preemtible: no

**Comment by Luschgy** [comment]
I also have this Problem, any help is appreciated

**Comment by jesusdiez** [comment]
Another affected here... 😞 

- One-Shot: checked/unchecked (happens on both)
- Windows: no
- Preemtible: checked/unchecked (happens on both)

No `node cleanup work` on logs either.

We tested different configurations, node retention times and in each of them we get the same error.
We also tried to rollback to previous plugin version but we had to update again as the old versión has a problem rolling up the new instance,  and tries again with a new one, and another one, and another one... 

Some logs:
```
Dec 09, 2019 6:54:06 PM null
FINEST: Instance agent-app-qght92 is running and ready...
Dec 09, 2019 6:54:06 PM null
INFO: Launching instance: agent-app-qght92
Dec 09, 2019 6:54:06 PM null
INFO: bootstrap
Dec 09, 2019 6:54:06 PM null
INFO: Getting keypair...
Dec 09, 2019 6:54:06 PM null
INFO: Using autogenerated keypair
Dec 09, 2019 6:54:06 PM null
INFO: Authenticating as jenkins
Dec 09, 2019 6:54:07 PM null
INFO: Connecting to 35.X.Y.Z on port 22, with timeout 10000.
Dec 09, 2019 6:54:17 PM null
INFO: Failed to connect via ssh: The kexTimeout (10000 ms) expired.
Dec 09, 2019 6:54:17 PM null
INFO: Waiting for SSH to come up. Sleeping 5.
Dec 09, 2019 6:54:22 PM null
INFO: Connecting to 35.X.Y.Z on port 22, with timeout 10000.
Dec 09, 2019 6:54:26 PM null
WARNING: Failed to verify server host key because no host key metadata was available: 404 Not Found
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "The resource 'hostkeys/' of type 'Guest Attribute' was not found."
   }
  ],
  "code": 404,
  "message": "The resource 'hostkeys/' of type 'Guest Attribute' was not found."
 }
}

Dec 09, 2019 6:54:26 PM null
INFO: Connected via SSH.
Dec 09, 2019 6:54:26 PM null
INFO: Verifying: java -fullversion
openjdk full version "1.8.0_181-8u181-b13-2~deb9u1-b13"
Dec 09, 2019 6:54:26 PM null
INFO: Copying agent.jar to: /tmp
Dec 09, 2019 6:54:27 PM null
INFO: Launching Jenkins agent via plugin SSH: java -jar /tmp/agent.jar
<===[JENKINS REMOTING CAPACITY]===>Remoting version: 3.36
This is a Unix agent
Evacuated stdout
Instance agent-app-qght92 is preemptive, setting up preemption listener
Preemptive instance, listening to metadata for preemption event
Agent successfully connected and online
ERROR: Connection terminated
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3156)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:862)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
```

**Comment by craigdbarber** [comment]
Hi @mattdlh sorry to hear you're encountering issues. Could you please share some more info to help us better diagnose this:
* GCE Plugin Version
* Jenkins Version
* List of other installed plugins/versions

Thanks.

**Comment by craigdbarber** [comment]
@jesusdiez thanks for sharing the log. Just as an FYI, the log warning: "Failed to verify server host key because no host key metadata" **does not** indicate a job failure. It's just the plugin letting you know that it can't verify the server's ssh host key coming from this line: https://github.com/jenkinsci/google-compute-engine-plugin/blob/a654acd5bc9d912847462782bcd2f48fd94130cd/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineComputerLauncher.java#L429

I've created an issue to help clear this up in the log's message: #168

Similar to the above comment, could you please provide us with some more env information to help us hunt down this issue.

**Comment by jesusdiez** [comment]
@craigdbarber Thanks for the info! I already supposed that but didn't find a place in the config to  to disable that check. I've updated my original comment with the versions and installed plugins. Let me know if I can help debugging that in any way.

**Comment by jesusdiez** [comment]
@craigdbarber , we've been checking and the instance **also gets stopped** when no `agent.jar` process is running on it, or even when the jenkins service is stopped on master host... and also when both are happening: we forced everything trying to discover what is happening.

We're thinking about something that is being predefined on the instance creation that makes it get automatically stopped after around 7 minutes (we have no `startup script` on our cloud definition).

![stackdriver-agent](https://user-images.githubusercontent.com/393104/70523380-368a1800-1b43-11ea-86a1-5e9df7806f4d.png)

**Comment by craigdbarber** [comment]
@jesusdiez could you try rolling back to a previous version to see if the issue is still occurring?

**Comment by craigdbarber** [comment]
Separately, I'd suggest following this troubleshooting guide on the topic to see if it helps alleviate the issue: https://wiki.jenkins.io/display/JENKINS/Remoting+issue
If one of the steps they recommend does help, please do follow up here with the info.

**Comment by jesusdiez** [comment]
> @jesusdiez could you try rolling back to a previous version to see if the issue is still occurring?

We had to recover an old snapshot of the jenkins machine. We've been very conservative on this specific plugin updates, as we've suffered other bugs in the past. We were forced to update from 1.0.10 to 4.20 because we did other non-bc (ha!) system plugins update and each execution was creating infinite agent machines (something was broken on the master-agent connectivity and it didn't detect the new instance, creating a new one). We rolled back to the 1.0.10 and the multiple instance problem was happening again, so we had to roll back the rollback.

I'll check the Remoting Issue link you provided, as it looks very related to our scenario.

**Comment by mattdlh** [comment]
@craigdbarber 

GCE Plugin Version: 4.2.0 and we have tried downgrading to 4.1.1 with the same issue.
Jenkins Version: 2.190.3
List of other installed plugins/versions:

```
plugins,ace-editor,ghprb,antisamy-markup-formatter,branch-api,build-monitor-plugin,build-pipeline-plugin,build-user-vars-plugin,cloudbees-folder,conditional-buildstep,copyartifact,credentials-binding,credentials,git,durable-task,external-monitor-job,gerrit-trigger,gerrit,git-client,git-server,cvs,github-api,github-branch-source,plot,github-oauth,github-organization-folder,github-pullrequest,github,greenballs,handlebars,html5-notifier-plugin,icon-shim,javadoc,jquery-detached,jquery,junit,slack,log-parser,mailer,mapdb-api,matrix-auth,matrix-combinations-parameter,matrix-project,maven-plugin,momentjs,pam-auth,parameterized-trigger,phabricator-plugin,pipeline-build-step,pipeline-input-step,pipeline-rest-api,pipeline-stage-step,pipeline-stage-view,plain-credentials,ldap,promoted-builds,publish-over-ssh,run-condition,sauce-ondemand,scm-api,scm-sync-configuration,scp,script-security,ec2,sloccount,ssh-agent,ssh-credentials,ssh-slaves,statusmonitor,structs,subversion,test-results-analyzer,thinBackup,token-macro,translation,valgrind,windows-slaves,workflow-aggregator,workflow-api,workflow-basic-steps,workflow-cps-global-lib,workflow-cps,workflow-durable-task-step,workflow-job,workflow-multibranch,workflow-scm-step,workflow-step-api,workflow-support,covcomplplot,ant,view-job-filters,jsch,robot,jira,ansicolor,audit-trail,bouncycastle-api,http-post,docker-plugin,blueocean,package-drone,cobertura,build-timeout,node-iterator-api,timestamper,aws-credentials,pipeline-milestone-step,jackson2-api,docker-build-step,pipeline-stage-tags-metadata,blueocean-jwt,pipeline-model-declarative-agent,azure-commons,urltrigger,artifactdeployer,artifact-promotion,favorite,docker-commons,blueocean-web,pipeline-model-api,pipeline-model-extensions,aws-java-sdk,ansible,pipeline-graph-analysis,docker-workflow,metrics,cloud-stats,authentication-tokens,pipeline-github-lib,nexus-artifact-uploader,display-url-api,git-parameter,envinject,build-env-propagator,pipeline-model-definition,azure-credentials,performance,accelerated-build-now-plugin,azure-vm-agents,htmlpublisher,blueocean-jira,blueocean-config,blueocean-i18n,variant,sse-gateway,command-launcher,build-timestamp,rebuild,postbuild-task,blueocean-events,benchmark,blueocean-rest,blueocean-core-js,jdk-tool,envinject-api,pubsub-light,ws-cleanup,blueocean-dashboard,lockable-resources,email-ext,blueocean-bitbucket-pipeline,job-restrictions,docker-java-api,publish-over,blueocean-git-pipeline,jenkins-design-language,file-operations,blueocean-pipeline-scm-api,blueocean-pipeline-editor,mercurial,blueocean-display-url,blueocean-pipeline-api-impl,blueocean-commons,blueocean-autofavorite,blueocean-github-pipeline,blueocean-personalization,blueocean-rest-impl,apache-httpcomponents-client-4-api,cloudbees-bitbucket-branch-source,trilead-api,google-oauth-plugin,scoring-load-balancer,oauth-credentials,google-metadata-plugin,code-coverage-api,blueocean-executor-info,clang-scanbuild,google-storage-plugin,resource-disposer,flexible-publish,any-buildstep,elastic-axis,handy-uri-templates-2-api,google-compute-engine,google-cloudbuild,
```

**Comment by isabellf** [comment]
I am getting the same issue. 
I setup a staging server that was working properly but when I re-built it for production it didn't.
Since I still have the staging server around, I was able to compare the plug versions.

Jenkins ver. 2.208
The unexpected thing is that both are using GCE Plugin Version: 4.2.0

```
--- plugins.working     2019-12-14 08:59:13.000000000 -0500
+++ plugins.failing       2019-12-14 08:58:55.000000000 -0500
@@ -1,4 +1,4 @@
-iace-editor    1.1     true
+ace-editor     1.1     true
 ant    1.10    true
 antisamy-markup-formatter      1.6     true
 apache-httpcomponents-client-4-api     4.5.10-2.0      true
@@ -25,46 +25,49 @@
 blueocean-rest-impl    1.21.0  true
 blueocean-web  1.21.0  true
 bouncycastle-api       2.17    true
-branch-api     2.5.4   true
+branch-api     2.5.5   true
+built-on-column        1.1     true
 cisco-spark-notifier   1.1.1   true
-cloudbees-bitbucket-branch-source      2.5.0   true
-cloudbees-folder       6.9     true
-command-launcher       1.3     true
+cloudbees-bitbucket-branch-source      2.6.0   true
+cloudbees-folder       6.10.0  true
+command-launcher       1.4     true
 conditional-buildstep  1.3.6   true
 credentials    2.3.0   true
 credentials-binding    1.20    true
 display-url-api        2.3.2   true
 docker-commons 1.15    true
-docker-workflow        1.20    true
-durable-task   1.30    true
+docker-workflow        1.21    true
+durable-task   1.33    true
 email-ext      2.68    true
+envinject      2.3.0   true
+envinject-api  1.7     true
 external-monitor-job   1.7     true
 favorite       2.3.2   true
-git    3.12.1  true
-git-client     2.9.0   true
-git-server     1.8     true
-github 1.29.4  true
+git    4.0.0   true
+git-client     3.0.0   true
+git-server     1.9     true
+github 1.29.5  true
 github-api     1.95    true
 github-branch-source   2.5.8   true
 google-compute-engine  4.2.0   true
-google-metadata-plugin 0.2     true
+google-metadata-plugin 0.3.1   true
 google-oauth-plugin    1.0.0   true
 google-storage-plugin  1.5.1   true
 handlebars     1.1.1   true
-handy-uri-templates-2-api      2.1.7-1.0       true
+handy-uri-templates-2-api      2.1.8-1.0       true
 htmlpublisher  1.21    true
-jackson2-api   2.10.0  true
+jackson2-api   2.10.1  true
 javadoc        1.5     true
-jdk-tool       1.3     true
+jdk-tool       1.4     true
 jenkins-design-language        1.21.0  true
-jira   3.0.10  true
+jenkins-multijob-plugin        1.32    true
+jira   3.0.11  true
 jquery 1.12.4-1        true
 jquery-detached        1.2.1   true
-jquery-ui      1.0.2   true
 jsch   0.1.55.1        true
 junit  1.28    true
 ldap   1.21    true
-lockable-resources     2.5     true
+lockable-resources     2.7     true
 mailer 1.29    true
 mapdb-api      1.0.9.0 true
 matrix-auth    2.5     true
@@ -74,23 +77,23 @@
 momentjs       1.1.1   true
 monitoring     1.80.0  true
 nodelabelparameter     1.7.2   true
-oauth-credentials      0.3     true
+oauth-credentials      0.4     true
 packer 1.5     true
-pam-auth       1.5.1   true
+pam-auth       1.6     true
 Parameterized-Remote-Trigger   3.1.0   true
-parameterized-trigger  2.35.2  true
+parameterized-trigger  2.36    true
 periodicbackup 1.5     true
-pipeline-build-step    2.9     true
+pipeline-build-step    2.10    true
 pipeline-graph-analysis        1.10    true
 pipeline-input-step    2.11    true
 pipeline-milestone-step        1.3.1   true
-pipeline-model-api     1.3.9   true
+pipeline-model-api     1.5.0   true
 pipeline-model-declarative-agent       1.1.1   true
-pipeline-model-definition      1.3.9   true
-pipeline-model-extensions      1.3.9   true
+pipeline-model-definition      1.5.0   true
+pipeline-model-extensions      1.5.0   true
 pipeline-rest-api      2.12    true
 pipeline-stage-step    2.3     true
-pipeline-stage-tags-metadata   1.3.9   true
+pipeline-stage-tags-metadata   1.5.0   true
 pipeline-stage-view    2.12    true
 pipeline-utility-steps 2.3.1   true
 plain-credentials      1.5     true
@@ -98,7 +101,7 @@
 role-strategy  2.15    true
 run-condition  1.2     true
 scm-api        2.6.3   true
-script-security        1.66    true
+script-security        1.68    true
 sse-gateway    1.20    true
 ssh-credentials        1.18    true
 ssh-slaves     1.31.0  true
@@ -107,18 +110,18 @@
 tap    2.3     true
 test-results-analyzer  0.3.5   true
 timestamper    1.10    true
-token-macro    2.8     true
+token-macro    2.10    true
 trilead-api    1.0.5   true
 variant        1.3     true
 windows-slaves 1.5     true
 workflow-aggregator    2.6     true
-workflow-api   2.37    true
+workflow-api   2.38    true
 workflow-basic-steps   2.18    true
-workflow-cps   2.74    true
+workflow-cps   2.78    true
 workflow-cps-global-lib        2.15    true
-workflow-durable-task-step     2.34    true
-workflow-job   2.35    true
+workflow-durable-task-step     2.35    true
+workflow-job   2.36    true
 workflow-multibranch   2.21    true
 workflow-scm-step      2.9     true
-workflow-step-api      2.20    true
+workflow-step-api      2.21    true
 workflow-support       3.3     true
```

**Comment by isabellf** [comment]
For the record, I found out the culprit in my installation, the cloud instanceId/jenkins_cloud_id 
 in the config file. It was duplicate! As a result, the working instance (which was idle), ended up cleaning up the *apparently* orphaned slave instances.
```
2019-12-14 19:50:58.781+0000 [id=30821] INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished PeriodicBackup. 0 ms
2019-12-14 19:51:20.206+0000 [id=22]    INFO    c.g.j.p.c.CleanLostNodesWork#terminateInstance: Remote instance gce1-slave-xpn-rmjstp not found locally, removing it
2019-12-14 19:51:58.780+0000 [id=30829] INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started PeriodicBackup
```
So for me, this issue is gone and my advice is too verify your cloud config XML.

**Comment by Luschgy** [comment]
@isabellf could you post your config XML for comparision ?

**Comment by androa** [comment]
I'm having this issue as well with preemtible nodes. 

At first this error message made me suspect it might be some kind of timeout issue with the HTTP call for getting the preemptible signal:

```
Jan 06, 2020 10:56:20 AM WARNING com.google.jenkins.plugins.computeengine.ComputeEngineComputer getPreempted
Error when getting preempted status
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to jenkins-generic-kq94mo
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:957)
		at com.google.jenkins.plugins.computeengine.ComputeEngineComputer.getPreemptedStatus(ComputeEngineComputer.java:62)
		at com.google.jenkins.plugins.computeengine.ComputeEngineComputer.lambda$onConnected$0(ComputeEngineComputer.java:55)
		at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
		at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
		at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.google.jenkins.plugins.computeengine.PreemptedCheckCallable.call(PreemptedCheckCallable.java:74)
	at com.google.jenkins.plugins.computeengine.PreemptedCheckCallable.call(PreemptedCheckCallable.java:34)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Caused: java.lang.RuntimeException
	at com.google.jenkins.plugins.computeengine.ComputeEngineComputer.getPreemptedStatus(ComputeEngineComputer.java:71)
	at com.google.jenkins.plugins.computeengine.ComputeEngineComputer.lambda$onConnected$0(ComputeEngineComputer.java:55)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused: java.util.concurrent.ExecutionException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.google.jenkins.plugins.computeengine.ComputeEngineComputer.getPreempted(ComputeEngineComputer.java:102)
	at com.google.jenkins.plugins.computeengine.ComputeEngineRetentionStrategy.wasPreempted(ComputeEngineRetentionStrategy.java:113)
	at com.google.jenkins.plugins.computeengine.ComputeEngineRetentionStrategy.taskCompleted(ComputeEngineRetentionStrategy.java:83)
	at hudson.slaves.SlaveComputer.taskCompleted(SlaveComputer.java:355)
	at hudson.model.queue.WorkUnitContext.synchronizeEnd(WorkUnitContext.java:140)
	at hudson.model.Executor.finish1(Executor.java:477)
	at hudson.model.Executor.run(Executor.java:451)
```

But I set up a cURL-call to the same endpoint, without any issues. I also get the `TRUE` response when the node is set into maintenance mode.

The log for the node says:

```Jan 05, 2020 11:35:55 AM null
INFO: Launching Jenkins agent via plugin SSH: java -jar /tmp/agent.jar
<===[JENKINS REMOTING CAPACITY]===>Remoting version: 3.33
This is a Unix agent
Evacuated stdout
Instance jenkins-generic-kq94mo is preemptive, setting up preemption listener
Preemptive instance, listening to metadata for preemption event
Agent successfully connected and online
ERROR: Connection terminated
java.io.EOFException
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2763)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3258)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:873)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:350)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:140)
	at hudson.remoting.Command.readFrom(Command.java:126)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:36)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
```

To me it seems very much as the agent is killed instantly and gets no chance to clean up (or inform the master about the preemption event).

**Comment by androa** [comment]
I've been going at this issues from a couple of different angles and tried to pinpoint exactly what causes this behaviour.

So far I've gathered that Jenkins connects to the GCP node over SSH, copies the agent/remoting jar, and runs it. It then starts an async task/future on that machine to listen for the "preemtive" event in the GCP API.

The issue I'm seeing is that no matter how I turn off the node and/or the agent, the Jenkins agent dies immediately, leaves the SSH connection open for a while, and the task which listens to the preemtive event is killed.

I've tried simulating maintenance mode, simply stopping the node, executing `shutdown` in a shell, to killing the agent process with SIGTERM. They all result in the Jenkins agent to die instantly and give the `EOFException` showed above.

It seems the Jenkins agent dies too fast and is unable to to a controlled shutdown.

The nodes run Ubuntu 18.04 with `OpenJDK 11.0.5+10-post-Ubuntu-0ubuntu1.118.04`. The execution tree looks like this:

```
root      2546  0.0  0.0  72292  6548 ?        Ss   13:45   0:00 /usr/sbin/sshd -D
root     10096  0.0  0.0 107988  7164 ?        Ss   14:01   0:00  \_ sshd: jenkins [priv]
jenkins  10155  0.0  0.0 108252  4368 ?        S    14:01   0:00  |   \_ sshd: jenkins@notty
jenkins  10160  0.0  0.0   4624   808 ?        Ss   14:01   0:00  |       \_ sh -c java -jar /tmp/agent.jar
jenkins  10161  1.7  0.1 36050392 154052 ?     Sl   14:01   0:07  |           \_ java -jar /tmp/agent.jar
```

**Comment by hmeerlo** [comment]
Anyone ever found a solution for this problem? It happens a lot for me, really annoying

**Comment by nehaljwani** [comment]
In my case, I had a test instance of Jenkins which was basically a clone and hosted behind a different end point. Although all jobs were disabled on it, the plugin was quite active and reaping off slaves. The comment by @fisabelle solved the mystery, along with https://github.com/jenkinsci/google-compute-engine-plugin/issues/46

**Comment by robertauer** [comment]
I am currently having the same problem. Reading the posts above I looked into my `config.xml` and found the following:
```xml
  <clouds>
    <com.google.jenkins.plugins.computeengine.ComputeEngineCloud plugin="google-compute-engine@4.3.3">
...
<instanceId>abcdefgh-1234-1234-1234-abcdefghijkl</instanceId>
...
          <googleLabels>
            <entry>
              <string>jenkins_cloud_id</string>
              <string>abcdefgh-1234-1234-1234-abcdefghijkl</string>
            </entry>
            <entry>
              <string>jenkins_config_name</string>
              <string>name123</string>
            </entry>
          </googleLabels>
...
    </com.google.jenkins.plugins.computeengine.ComputeEngineCloud>
  </clouds>
```
I guess this is what @fisabelle is talking about. Could you please tell us how you fixed it? Do I remove the `<instanceId>` part or the `<string>jenkins_cloud_id</string>` entry part?
**EDIT:** I removed the `<instanceId>` line and it fixed the problem for now.

**Comment by rkirkpat** [comment]
I can confirm @robertauer solution above. 

We were testing a new controller with a backup from our production controllers and were seeing GCP agents launched by both to run jobs being killed prematurely. Reviewing the GCP Compute Engine audit logs showed that the "other" Jenkins controllers was doing the kills (confirmed by source IP addresses of the destroy requests).

The solution was to shutdown the test controller, edit its config to remove the `instanceID` line as @robertauer shows in his comment above, then restart the controller. A new instance id was then generated and all the google label entries were updated with this new id as well. After doing this we had no more conflict between controllers on agents. 

A feature request would then be a button in the web UI to reset this instance id, or at least a warning in the documentation about this.

**Comment by johanblumenberg** [comment]
I encountered the exact same issue today. VMs shut down mid build, always at the same minute of the hour. I checked the `instanceId` value in the configuration, and turns out I had two cloud configurations with the same ID.

Fixing the duplicate ID seems to fix the problem.

The problem started when I made a copy of a cloud configuiration. When you choose "Copy Existing Cloud" to create a new cloud configuration, it looks like it copies the entire configuration of the other cloud, including the `instanceId` value.

**Comment by mtellezj** [comment]
@johanblumenberg what Jenkins and GCP plugin version are you using?

**Comment by johanblumenberg** [comment]
> @johanblumenberg what Jenkins and GCP plugin version are you using?

Latest at the time of writing, `4.575.v6969b_7c435eb_`, Jenkins version `2.452.3`.

**Comment by YMalinov** [comment]
My organization has also experienced this bug several times throughout the years. We're currently running Jenkins version 2.462.3 and Google Compute Engine plugin 4.575.v6969b_7c435eb_ . It appears that changes in any of the Cloud node configurations from Jenkins's web UI leads to Jenkins rewriting this part in its config.xml file, causing the instance ID duplication issue. Would love to figure out a more permanent solution, which doesn't include us writing a script that manually removes these items from config.xml upon each configuration change.

**Comment by gbhat618** [comment]
The being open since 2019, and multiple changes to orphan cleanup since then. The root case of each report is likely different.
With the latest fix in orphan cleanup - https://github.com/jenkinsci/google-compute-engine-plugin/releases/tag/4.820.v2209fb_d7a_261 - expecting no such issues to happen.

For how the orphan cleanup works see https://github.com/jenkinsci/google-compute-engine-plugin#orphan-agent-cleanup

Closing it for now. Lets open new issue if any problem surfaces post https://github.com/jenkinsci/google-compute-engine-plugin/releases/tag/4.820.v2209fb_d7a_261
