### ISSUE TITLE
java.lang.NullPointerException when choosing Boot Disk/Image Project

### ISSUE THREAD

**Issue by sharkannon** [jenkinsci/google-compute-engine-plugin#203]
It appears that when we try to use a custom boot disk image that we built, we get a Null Pointer exception when we select our internal project.  We can select the pre built ones (coreos-cloud, centos-cloud and the like) and the Image Name comes up.  But if we select our PROJECT Name we get

`2020-09-09 17:06:29.063+0000 [id=6327612]    WARNING    o.e.j.s.h.ContextHandler$Context#log: Error while serving https://jenkins/descriptorByName/com.google.jenkins.plugins.computeengine.InstanceConfiguration/fillBootDiskSourceImageNameItems
 java.lang.NullPointerException
     at com.google.cloud.graphite.platforms.plugin.client.ComputeClient.isDeprecated(ComputeClient.java:758)
     at com.google.cloud.graphite.platforms.plugin.client.ComputeClient.lambda$listImages$7(ComputeClient.java:214)
     at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
     at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
     at com.google.cloud.graphite.platforms.plugin.client.util.ClientUtil.processResourceList(ClientUtil.java:57)
     at com.google.cloud.graphite.platforms.plugin.client.ComputeClient.listImages(ComputeClient.java:212)
     at com.google.jenkins.plugins.computeengine.InstanceConfiguration$DescriptorImpl.doFillBootDiskSourceImageNameItems(InstanceConfiguration.java:853)
     at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
     at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
 Caused: java.lang.reflect.InvocationTargetException
     at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:400)
     at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
     at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
     at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
     at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
     at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
     at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
     at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
     at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
     at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
     at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
     at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
     at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
     at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
     at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:248)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
     at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
     at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
     at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
     at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
     at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
     at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
     at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
     at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:88)
     at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:114)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
     at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
     at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
     at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
     at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
     at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
     at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
     at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
     at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
     at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
     at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
     at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
     at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
     at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
     at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
     at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
     at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
     at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
     at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
     at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
     at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
     at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
     at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
     at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
     at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
     at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
     at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
     at org.eclipse.jetty.server.Server.handle(Server.java:500)
     at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
     at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
     at java.lang.Thread.run(Thread.java:748)`

Jenkins Version: 2.222.4
Plugin Version: 4.3.2 (Happens on 4.3.1 too, we just upgraded to see if it fixed things).

Double checked and the SA and everything has the appropriate access (Gave it owner just incase).  It was working prior to 4.3.1 (We don't use the images often, so we've updated the plugin a couple times since it was last used, so not sure of last working version).

**Comment by sharkannon** [comment]
Notes: Downgraded to 4.1.1 and still have the same issue.  Starting to wonder if we had an old config that just worked, we recently went into the "Clouds" config to modify some kubernetes containers and saved them.. and wondering if the plugin then resaved the config file and no longer works (Just thinking out loud).

**Comment by sharkannon** [comment]
i've been able to work around it by using a instance template, but this is still an issue.

**Comment by donmccasland** [comment]
Looking into it.
