### ISSUE TITLE
Windows VM get disconnected after some time

### ISSUE THREAD

**Issue by cristiandonosoc** [jenkinsci/google-compute-engine-plugin#206]
Hi,

We're using the plugin to provision builder windows VMs for Jenkins. Overall it works well except that machines tend to go offline after a day or two, without fail. I got around this by having a script that would detect offline machines and delete them, and spin new ones. But now I have long running jobs and invariably the machine would get disconnected in the middle. The only logs I can see from Jenkins is the following:

```
2020-09-22 03:46:04.944+0000 [id=2027898]	INFO	h.r.SynchronousCommandTransport$ReaderThread#run: I/O error in channel experimental-ozx4oy
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2738)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3213)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:896)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
	at hudson.remoting.Command.readFrom(Command.java:142)
	at hudson.remoting.Command.readFrom(Command.java:128)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
```

The slave log says pretty much the same thing:

```
2020-09-22 12:19:21.950 CLST ERROR: Connection terminated
2020-09-22 12:19:21.950 CLST java.io.EOFException
2020-09-22 12:19:21.950 CLST at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2738)
2020-09-22 12:19:21.950 CLST at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3213)
2020-09-22 12:19:21.950 CLST at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:896)
2020-09-22 12:19:21.950 CLST at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
2020-09-22 12:19:21.950 CLST at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
2020-09-22 12:19:21.950 CLST at hudson.remoting.Command.readFrom(Command.java:142)
2020-09-22 12:19:21.950 CLST at hudson.remoting.Command.readFrom(Command.java:128)
2020-09-22 12:19:21.950 CLST at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
2020-09-22 12:19:21.950 CLST at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
2020-09-22 12:19:21.950 CLST Caused: java.io.IOException: Unexpected termination of the channel
2020-09-22 12:19:21.950 CLST at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
```

This is being super disruptive to our setup, as its getting in the way of running long jobs. How could I go about debugging this?

**Comment by robinbanbury** [comment]
@cristiandonosoc have you disabled Windows updates?

I got a similar issue to you, and found that was the problem. If the VMs are all going offline at a similar time of day, it could be the issue.

As you are getting an `Unexpected termination of the channel` error, it suggests something other than the plugin might be killing the VMs.

You can disable automatic updates by setting `HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU\NoAutoUpdate` to `1` in the registry (Windows Server 2016).

**Comment by cristiandonosoc** [comment]
Indeed that was one of the cause of trouble. We disabled windows updated and the system got a lot more stable.

**Comment by robinbanbury** [comment]
Glad to hear the plugin is working better for you now :-) 

Ok to close this issue then?
