### ISSUE TITLE
plugin 4.3.2 does not work on Jenkins 2.259 (java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by cure** [jenkinsci/google-compute-engine-plugin#207]
This plugin is broken on Jenkins 2.259. I see this in the Jenkins logs:

> 2020-09-29 20:47:02.217+0000 [id=40]  SEVERE  hudson.triggers.SafeTimerTask#run: Timer task hudson.slaves.NodeProvisioner$NodeProvisionerInvoker@5a63812b failed
java.lang.IllegalArgumentException: The specified method is not declared by the specified base class (hudson.slaves.CloudProvisioningListener), or it is private, static or final.
  at hudson.Util.isOverridden(Util.java:1456)
  at hudson.Util.ifOverridden(Util.java:1480)
  at hudson.slaves.CloudProvisioningListener.canProvision(CloudProvisioningListener.java:45)
  at hudson.slaves.CloudProvisioningListener.canProvision(CloudProvisioningListener.java:65)
  at hudson.slaves.NodeProvisioner$StandardStrategyImpl.apply(NodeProvisioner.java:723)
  at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:334)
  at hudson.slaves.NodeProvisioner.access$900(NodeProvisioner.java:64)
  at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:823)
  at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
  at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

Downgrading to Jenkins 2.253 resolves the issue for me.

**Comment by donmccasland** [comment]
Looking into it.
